config/routes.rb
Rails.application.routes.draw do

root "bicycles#home"
get "bicycles" => "bicycles#home"
get "bicycles/new" => "bicycles#new", as: :new
get "bicycle/:id/edit" => "bicycles#edit", as: :edit_bicycle
post "bicycles" => "bicycles#create"
patch "bicycle/:id" => "bicycles#update"
delete "bicycle/:id" => "bicycles#destroy"
get "bicycle/:id" => "bicycles#show", as: :bicycle

end

app/models/bicycle.rb
class Bicycle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
	def edit
		@bicycle = Bicycle.find(params[:id])
	end

	def home
		@bicycles = Bicycle.all
	end

	def show
		@bicycle = Bicycle.find(params[:id])
	end

	def new
		@bicycle = Bicycle.new
	end

	def create

		@bicycle = Bicycle.new(params.require(:bicycle).permit(:price, :style, :color))

		if @bicycle.save
			redirect_to root_url

		end
	end

	def update
		@bicycle = Bicycle.find(params[:id])

		if @bicycle.update_attributes(params.require(:bicycle).permit(:price, :style, :color))
			redirect_to root_url
		else
			render "edit"
		end
	end


	def destroy
		@bicycle = Bicycle.find(params[:id])
		@bicycle.destroy
	redirect_to root_url
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/views/bicycles/edit.html.erb
<h1>Edit this Bicycle</h1>
<%= form_for @bicycle do |f| %>

Price: <%= f.text_field :price %>
Style: <%= f.text_field :style %>
Color: <%= f.text_field :color %>

<%= f.submit "Edit bicycle now" %>

<% end %>

<%= link_to "Back to list of bicycles", root_url %>

app/views/bicycles/home.html.erb
<h1>Welcome to A.S.S. Bike Shop</h1>

<ul>
	<% @bicycles.each do |bicycle| %>

	<li><%= bicycle.price %> 
		<%= bicycle.style %>
		<%= bicycle.color %>
		<%= link_to "show this bike", bicycle_path(bicycle) %>
		<%= link_to "Edit this bike", edit_bicycle_path(bicycle) %>

	</li>

		<% end %>
</ul>

<%= link_to "add a bike", new_path %>

app/views/bicycles/new.html.erb
<h1>Add a bike</h1>

<%= form_for @bicycle do |f| %>
Price:<%= f.text_field :price %>
Style:<%= f.text_field :style %>
Color:<%= f.text_field :color %>

<%= f.submit "Add a bike" %>

<% end %>

app/views/bicycles/show.html.erb
		

		<%= @bicycle.price %> 
		<%= @bicycle.style %>
		<%= @bicycle.color %>

<%= link_to "Delete this ass bike", :bicycle, method: :delete, data: {confirm: "Are you sure you want to delete this ass bike?"} %>

<%= link_to "Back to our bikes", root_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css">
  <title>Bike</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
    <div class="container">
      <img src="http://i62.tinypic.com/21lk042.jpg" width="200">
    </div>
  </div>

<%= yield %>

<!-- <div class="footer">
    <div class="container">
      <ul class="list-inline">
        <li><%= link_to "", "" %></li> <li><%= link_to "", "" %></li> <li><%= link_to "", "" %></li>
        <li><%= link_to "", "" %></li>
      </ul>
    </div>
  </div> -->

</body>
</html>